Fixed rubygems dependency.
Step 6/18 : RUN gem install sass
 ---> Running in f30118d17c02
Building native extensions.  This could take a while...
ERROR:  Error installing sass:
        rb-inotify requires Ruby version >= 2.2.